### PR TITLE
Card menu button colour change for on hover

### LINKED ISSUE #12: Album on mouse over menu is hidden when using a custom theme
When mousing over an album with a custom theme applied, the menu does not show. See image below.

### PR DESCRIPTION
**Pull request by chrismou**
Fixes #12 

Before:
screenshot 2016-03-11 16 47 05

After:
screenshot 2016-03-11 16 52 02

(Screenshot doesn't include the mouse, so you'll have to take my word for the fact I was hovering when I took them :wink:)

### CODE REVIEW

**Comment by chrismou** [comment]
I'm PRing this now because it's done, but I'm inevitably going to need to rebase it once #12 is merged in.

As a side note, do I have perms to push updates out to NPM?  I have repo merge permissions, but I'm not sure what's involved in getting a tag to NPM, if anything.  I figured it would be like packagist and pick tags up automatically, but the other day you made it sound like there was more involved.

**Comment by chrismou** [comment]
Ah balls, I think I've screwed the rebase :confused: 

I'm not sure I've ever actually rebased a PR in a situation like this - so I make my changes, generate `dist/` files and PR. Someone else PRs afterwards, they get merged in, then I need to fix my PR to include the changes, but also generate a new set of `/dist` files. What's the best way of achieving this?

TBH, in this case I'm probably better just putting in a new PR seeing as it was only a one liner, but for future reference, any suggestions?

**Comment by MarshallOfSound** [comment]
I always do this in this situation

``` bash
git fetch
git rebase origin/master
```

Then you will hit conflicts.  Any `src` conflict fix manually, ignore dist conflicts and just run `npm run build`.  Then do `git add . && git rebase --continue`

You might have to do that multiple times but it should get there in the end :)

**Comment by chrismou** [comment]
I did a `git pull --rebase origin master`.  Maybe that was my mistake.

Anyways, I'll redo this PR and pretend this never happened... 

`*whistles*`
`*walks away slowly*`

**Comment by chrismou** [comment]
TBH, in hindsight, I think I just confused Github.  It's showing 2 of @twolfson's commits in the list, but when you go to the changes tab it only showed my changes.  So it will have worked out OK in the end.

Ah well, done now. New PR incoming.

**Comment by twolfson** [comment]
Yea, you should have been fine with a squash and force push =/

Either via `git rebase -i origin/master` and pick lots of "squash"

Or something like https://github.com/twolfson/git-sqwish

**Pull request closed without merging**
