### PR TITLE
Add ability to use dynamic alpha and darkness variables from our strange CSS syntax :laughing:

### PR DESCRIPTION
**Pull request by MarshallOfSound**
Nothing changes here UI wise, just behind the scenes to make it easier to add custom alpha and darkness modifiers without having to add new color identifiers each time.

/cc @gmusic-utils/gmusic-js

### CODE REVIEW

**Comment by twolfson** [comment]
I think you are pushing the boundaries of regexps. Maybe we should switch to EJS/_.template? That way you can define custom functions at the top of the template (or pass in a helpers object (e.g. `helpers.darken`))

**Comment by MarshallOfSound** [comment]
The core problem with using pre-existing templating tools is that they break when put through a CSS parser.  For instance EJS `"<% "` will break a CSS parser.

That's why a very long time ago 😄 we ended up using our own internal regexp system

**Comment by twolfson** [comment]
EJS uses `<%` by default but its open/close tags can be switched out. I thought we used regexp due to it keeping things simple and small but now it looks like we are getting complex.

**Comment by MarshallOfSound** [comment]
Well, yeah, the fact that this is super lightweight is nice (only a few regexps) and with these two regexps modified I don't see us needing any other regexps.

I.e. We can insert colors, invert colors, lighten colors and darken colors

That's pretty much the extent of all possible color modifications 😆

**Comment by twolfson** [comment]
I'm afk at the moment but go look at _.template. It's super tiny and will
do everything you need.

**Pull request closed without merging**
