### PR TITLE
Fix podcast badge to respect theme

### PR DESCRIPTION
**Pull request by thedeany**

### CODE REVIEW

**Comment by jostrander** [comment]
I'm just going to throw it out there that @MarshallOfSound mentioned using `rgba()` instead of `transparent` on gitter, which is why it's changed here.

**Comment by thedeany** [comment]
@jostrander Thanks, I should have made that distinction.

**Comment by jostrander** [comment]
LGTM :+1: subbed this PR in over at GPMDP and tested working.

**Comment by MarshallOfSound** [comment]
@thedeany Can you quickly post some "before" / "after" screenshots?

**Comment by jostrander** [comment]
image
image

Before & After - underline is my fault, was hovering when took screenshot

**Comment by MarshallOfSound** [comment]
LGTM :+1:

**Comment by jostrander** [comment]
@MarshallOfSound can we get a land and release on this so we can update GPMDP? :grinning:

**Comment by MarshallOfSound** [comment]
Landed in `1.1.5`

**Pull request merged**
