### PR TITLE
Fixed loader and slider colors when using the lite version of material-ui

### PR DESCRIPTION
**Pull request by MarshallOfSound**
Quick fix for google falling back to material-lite implementations on the volume slider and loading spinner.

I can't get screenshots of the loading spinner as it disappears to quickly :cry: 

Before
before_slide

After
after_slide

/cc @gmusic-utils/gmusic-js

### CODE REVIEW

**Comment by twolfson** [comment]
lgtm :shipit:

**Comment by MarshallOfSound** [comment]
Bonus points for epic response time @twolfson 

You beat travis-ci....

**Comment by twolfson** [comment]
:gun: :dash:

**Comment by MarshallOfSound** [comment]
Published in `1.0.15`

**Comment by chrismou** [comment]
Good spot!

FYI, chrome dev tools has a throttling feature that's super useful for catching loading screenshots.  I've got a custom profile set up for 1kb/s transfer with a 1000ms latency ;-)

**Comment by MarshallOfSound** [comment]
@chrismou Yeah, I tried to nab it with that network latency setting (I had to in order to find the new class to add)  But then I resumed I couldn't nab it again :smile: 

I think it was fetching from a local cache or something and not doing network magic at all :cry:

**Comment by chrismou** [comment]
Ah well, at least you got that far. Xcode's Safari dev tools doesn't even allow you to see the styles of the element you're inspecting.

Yeah yeah, I know, Electron :wink:

**Comment by MarshallOfSound** [comment]
Electron's great :+1: 

I actually just released my first electron based version of GPMDP you should check it out :+1: 
http://www.googleplaymusicdesktopplayer.com/

**Comment by chrismou** [comment]
Wowzer, you knocked that out quick. Or did you? I've lost all track of time recently. Good work though, I'll check it out.

**Comment by MarshallOfSound** [comment]
@chrismou Solid month and a half I think.  I don't even know, it all blurred together :smile:

**Pull request merged**
