### PR TITLE
Color the shuffle / repeat buttons correctly

### LINKED ISSUE #6: Shuffle and repeat buttons are not being styled
As you can see in the attached image the repeat / shuffle buttons are not receiving the custom highlight coloring

oops

### PR DESCRIPTION
**Pull request by MarshallOfSound**
Added the shuffle and repeat buttons to the same selector group GPM uses so they get the new highlight color

Fixes #6

/cc @gmusic-utils/gmusic-theme-js @gmusic-utils/gmusic-js 

A very simple change, but gotta follow them contributing guidelines :100:

### CODE REVIEW

**Comment by chrismou** [comment]
Looks OK to me :+1:

**Comment by twolfson** [comment]
Looks good to me as well :shipit: 

For future reference, I don't think we had to open #6; screenshots of before/after in the PR would have sufficed as well

**Comment by MarshallOfSound** [comment]
Published in `1.0.10`

Thanks guys

**Comment by twolfson** [comment]
Heh, I consider that a minor update since it's not updating tests nor docs.

As a heads up, I noticed that there's no CHANGELOG in this repo. It might be good to add one so someone can easily tell what has changed.

**Comment by MarshallOfSound** [comment]
@twolfson , yeah I'll add a changelog shortly.  In regards to versioning, I've always gone off

<major>.<minor>.<patch>

Increment major of not backwards compatible (or massive array of new features)
Increment minor for a new feature
Increment patch for bugfixes

What scheme do you go off?

**Comment by twolfson** [comment]
Yea, I follow SemVer as well. However, I'm pretty strict about the definition of "bugfix".

If there's any possibility of it breaking existing setups (i.e. it changed anything outside of docs/tests), then I will do a minor release.

Your decision was totally fine; sometimes the line becomes more gray (e.g. updating a private function signature).

**Pull request merged**
