### PR TITLE
Fix for custom explicit colour

### LINKED ISSUE #46: Explicit has lost theming!
Explicit has lost it's theming 
image

Version 3.3.0

### PR DESCRIPTION
**Pull request by chrismou**
Fixes #46 

Google look to have changed the element for the explicit icon. This PR targets the new selector.

The PR is huge. Seem to still be having the same line endings issues as I did in #29.  Fairly sure it just depends on what OS the previous committer used when they ran the build script 😧

### CODE REVIEW

**Comment by jostrander** [comment]
LGTM :+1:

**Comment by chrismou** [comment]
👍

**Comment by jostrander** [comment]
You want to land 1.1.10?

**Comment by chrismou** [comment]
Will do shortly. Just polishing another PR off before I switch back to that branch 😄

**Comment by jostrander** [comment]
:+1: Sounds good

**Pull request merged**
